name: Auto Create Issues

on:
  push:
    paths:
      - issue_template.yml  # This triggers the action whenever the issue template is updated.

jobs:
  create_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Parse issue template and create issues
        run: |
          cat issue_template.yml | yq e '.issues[] | {"title": .title, "body": .body, "labels": .labels}' -j | jq -c '.[]' | while read issue; do
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              -d "$issue"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
